import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';import{Character,createCharacter}from'./rules/newtrpg/schema';import{DIFFICULTIES,STAT_NAMES,StatName}from'./rules/newtrpg/constants';import{calculateStats,maxHp,physicalAttack,mentalAttack,difficulty}from'./rules/newtrpg/calculation';import{normalJudgement,opposedJudgement}from'./rules/newtrpg/judgement';import{rollExpression}from'./rules/newtrpg/dice';import{parseRegistrationString}from'./rules/newtrpg/items';import{applyExperience,missionExp}from'./rules/newtrpg/experience';import{endTurn}from'./rules/newtrpg/effects';import{exportAll,importAll,loadCharacters,loadNpcs,saveCharacter,saveNpc}from'./storage/indexedDb';import{checkForUpdate,watchOnlineStatus}from'./pwa/update';
const tabs=['대시보드','능력치','판정','전투','스킬','아이템','NPC','성장','백업','설정'];
function download(name:string,data:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function parseFrontmatter(md:string){const m=md.match(/^---\n([\s\S]*?)\n---/);const obj:any={}; if(m)for(const line of m[1].split('\n')){const mm=line.match(/^([^:]+):\s*(.*)$/); if(mm)obj[mm[1].trim()]=mm[2].trim().replace(/^['"]|['"]$/g,'')} return obj}
function App(){const[tab,setTab]=useState(tabs[0]);const[chars,setChars]=useState<Character[]>([]);const[npcs,setNpcs]=useState<Character[]>([]);const[selected,setSelected]=useState('');const[online,setOnline]=useState(navigator.onLine);const[dice,setDice]=useState('1d100');const[stat,setStat]=useState<StatName>('힘');const[diff,setDiff]=useState(60);const[msg,setMsg]=useState('');const c=chars.find(x=>x.id===selected)??chars[0];const stats=useMemo(()=>c?calculateStats(c):undefined,[c]);useEffect(()=>watchOnlineStatus(setOnline),[]);useEffect(()=>{loadCharacters().then(a=>{if(a.length){setChars(a);setSelected(a[0].id)}else{const n=createCharacter('첫 캐릭터');saveCharacter(n);setChars([n]);setSelected(n.id)}});loadNpcs().then(setNpcs as any)},[]);async function update(p:Partial<Character>){if(!c)return;const n={...c,...p,lastSavedAt:new Date().toISOString()};await saveCharacter(n);setChars(xs=>xs.map(x=>x.id===n.id?n:x));}
if(!c)return <main>불러오는 중...</main>;return <main><header><h1>NewTRPG 시트 관리자</h1><span className={online?'ok':'bad'}>{online?'온라인':'오프라인'}</span></header><p className="notice">시트 데이터는 현재 기기 IndexedDB에 저장됩니다. 앱/브라우저 데이터 삭제 시 사라질 수 있으니 JSON 백업을 내보내세요.</p><nav>{tabs.map(t=><button className={tab===t?'on':''}onClick={()=>setTab(t)}>{t}</button>)}</nav><section><select value={c.id}onChange={e=>setSelected(e.target.value)}>{chars.map(x=><option value={x.id}>{x.name}</option>)}</select><button onClick={async()=>{const n=createCharacter('새 캐릭터');await saveCharacter(n);setChars([...chars,n]);setSelected(n.id)}}>새 시트</button><p>마지막 저장: {new Date(c.lastSavedAt).toLocaleString()}</p>{msg&&<div className="result">{msg}</div>}
{tab==='대시보드'&&<div className="grid"><label>이름<input value={c.name}onChange={e=>update({name:e.target.value})}/></label><label>종족<input value={c.race}onChange={e=>update({race:e.target.value})}/></label><label>직업<input value={c.job}onChange={e=>update({job:e.target.value})}/></label><label>현재 HP<input type="number"value={c.currentHp}onChange={e=>update({currentHp:+e.target.value})}/></label><b>최대HP {maxHp(c)}</b><b>물리공격 {physicalAttack(c)}</b><b>정신/마법 {mentalAttack(c)}</b><button onClick={()=>update({currentHp:maxHp(c),recentResult:'전체 회복'})}>전체 회복</button><button onClick={()=>update(endTurn(c))}>턴 종료</button><textarea placeholder="메모" value={c.memo} onChange={e=>update({memo:e.target.value})}/></div>}
{tab==='능력치'&&<div>{STAT_NAMES.map(s=><div className="row"><b>{s}</b><input type="number"value={c.stats[s].base}onChange={e=>update({stats:{...c.stats,[s]:{...c.stats[s],base:+e.target.value}}})}/><span>최종 {stats![s].final}</span></div>)}</div>}
{tab==='판정'&&<div className="grid"><select value={stat}onChange={e=>setStat(e.target.value as StatName)}>{STAT_NAMES.map(s=><option>{s}</option>)}</select><select value={diff}onChange={e=>setDiff(+e.target.value)}>{DIFFICULTIES.map(([n,v])=><option value={v}>{n} {v}</option>)}</select><button onClick={()=>setMsg(JSON.stringify(normalJudgement(c,stat,diff)))}>일반 판정</button><button onClick={()=>setMsg('실제 난이도: '+difficulty(c,diff))}>난이도 계산</button><input value={dice}onChange={e=>setDice(e.target.value)}/><button onClick={()=>{try{setMsg(JSON.stringify(rollExpression(dice)))}catch(e:any){setMsg(e.message)}}}>커스텀 다이스</button>{npcs[0]&&<button onClick={()=>setMsg(JSON.stringify(opposedJudgement(c,stat,npcs[0],stat)))}>첫 NPC와 상대 판정</button>}</div>}
{tab==='전투'&&<div><button onClick={()=>update({currentHp:Math.max(0,c.currentHp-10),recentResult:'피해 10 적용'})}>피해 10</button><button onClick={()=>update({currentHp:Math.min(maxHp(c),c.currentHp+10),recentResult:'회복 10 적용'})}>회복 10</button><p>피해감소: {c.damageReductionBonus}</p></div>}
{tab==='스킬'&&<div><button onClick={()=>update({skills:[...c.skills,{id:crypto.randomUUID(),name:'커스텀 스킬',kind:'기타',description:'',level:1,effectType:'직접',hpCost:0,target:'자신',durationTurns:1}]})}>스킬 추가</button>{c.skills.map(s=><p>{s.name} <button onClick={()=>update({skills:c.skills.filter(x=>x.id!==s.id)})}>삭제</button></p>)}</div>}
{tab==='아이템'&&<div><input id="reg"placeholder="철검|일반|3|힘 +1, 물리공격력 +2"/><button onClick={()=>{const el=document.getElementById('reg')as HTMLInputElement;update({equipment:[...c.equipment,parseRegistrationString(el.value)]})}}>장비 추가</button>{c.equipment.map(i=><p>{i.name}: {i.effect}<button onClick={()=>update({equipment:c.equipment.filter(x=>x.id!==i.id)})}>제거</button></p>)}</div>}
{tab==='NPC'&&<div><button onClick={async()=>{const n={...createCharacter('NPC'),kind:'NPC'};await saveNpc(n as any);setNpcs([...npcs,n])}}>NPC 추가</button>{npcs.map(n=><p>{n.name} HP {n.currentHp}/{maxHp(n)}</p>)}</div>}
{tab==='성장'&&<div><button onClick={()=>{const r=applyExperience(c.level,c.experience,c.totalExperience,missionExp(1));update({level:r.level,experience:r.experience,totalExperience:r.totalExperience,adventurerRank:r.adventurerRank,statCoins:c.statCoins+r.statCoinsGained})}}>위험도1 임무 경험치</button><p>Lv {c.level} EXP {c.experience} 누적 {c.totalExperience} 등급 {c.adventurerRank}</p></div>}
{tab==='백업'&&<div className="grid"><button onClick={async()=>download('newtrpg-backup.json',JSON.stringify(await exportAll(),null,2))}>전체 백업 내보내기</button><button onClick={()=>download(`${c.name}.json`,JSON.stringify(c,null,2))}>현재 캐릭터 내보내기</button><textarea id="import"placeholder="JSON 또는 Obsidian frontmatter Markdown 붙여넣기"/><button onClick={async()=>{const v=(document.getElementById('import')as HTMLTextAreaElement).value; await importAll(JSON.parse(v)); location.reload()}}>전체 백업 가져오기</button><button onClick={async()=>{const v=(document.getElementById('import')as HTMLTextAreaElement).value; const raw=v.trim().startsWith('---')?{...createCharacter(parseFrontmatter(v).이름||parseFrontmatter(v).name||'가져온 시트'),...parseFrontmatter(v)}:JSON.parse(v); await saveCharacter(raw); location.reload()}}>캐릭터/Markdown 가져오기</button><button onClick={()=>download(`${c.name}.md`,`---\n이름: ${c.name}\n레벨: ${c.level}\n종족: ${c.race}\n직업: ${c.job}\n---\n${c.memo}`)}>Obsidian Markdown 내보내기</button><button className="danger" onClick={()=>confirm('기기 내 앱 데이터를 초기화합니다. 백업했나요?')&&indexedDB.deleteDatabase('newtrpg-sheet-manager')&&location.reload()}>앱 데이터 초기화</button></div>}
{tab==='설정'&&<div><button onClick={async()=>setMsg(await checkForUpdate())}>새 버전 확인</button><label><input type="checkbox"/> HP 0 미만 허용(향후)</label></div>}
</section></main>}
createRoot(document.getElementById('root')!).render(<App/>);
